name: chat_app
description: "A real time chat application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package depends on.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_crashlytics: ^4.3.5
  firebase_core: ^3.13.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.2
  intl: ^0.20.2

# Dependencies specify other packages that your package depends on.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Afacad-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Afacad-Light.ttf
          weight: 300
        - asset: assets/fonts/Afacad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Afacad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Afacad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Afacad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Afacad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Afacad-Black.ttf
          weight: 900
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900
